Fourth task
Sanlovty/first-week-tasks pull request #3
Opened 2022-04-07 16:48 UTC by Sanlovty

<img src="https://user-images.githubusercontent.com/68380831/162255485-b1401f4f-efd7-440b-a322-d3d2fe849aef.jpg" width="50%" height="50%"/>

2022-04-10 13:06 UTC, HazarD2311 requested changes

2022-04-10 13:06 UTC, HazarD2311 commented on lib/features/common/screens/codelab/codelab_screen.dart
> +    );
что-то не очень понял, забыл запушить контент?

2022-04-10 14:20 UTC, Sanlovty commented on lib/features/common/screens/codelab/codelab_screen.dart
> +    );
Подумал, что страница пустая и пройдя кодлабы нужно просто соблюдать их в проекте. "Контент кодлабы" в эпп баре меня не смутил))

2022-04-12 11:29 UTC, HazarD2311 commented on lib/features/common/screens/codelab/widgets/random_words_widget.dart
> +          if (i.isOdd) return const Divider();
а тут тоже .separated не подошёл бы?

2022-04-12 11:29 UTC, HazarD2311 commented on lib/features/common/screens/codelab/widgets/random_words_widget.dart
> +  final _biggerFont = const TextStyle(fontSize: 18.0);
linter тут разве не просит сделать
`const _biggetFont = TextStyle(fontSize: 18.0`?

и почему не через централизованные стили?

2022-04-12 11:38 UTC, Sanlovty commented on lib/features/common/screens/codelab/widgets/random_words_widget.dart
> +  final _biggerFont = const TextStyle(fontSize: 18.0);
Из-за коммента выше))

2022-04-12 12:01 UTC, Sanlovty commented on lib/features/common/screens/codelab/widgets/random_words_widget.dart
> +  final _biggerFont = const TextStyle(fontSize: 18.0);
Кстати, линтер не просит)

2022-04-15 03:27 UTC, merged